nm_pnumpang = str(input("Masukan Nama: "))
no_hp = int(input("Masukan Nomor HP: "))
tujuan = str(input("Tujuan anda: "))
jam_brkt = int(input("Jam berangkat: "))
mnt_brkt = int(input("Menit Berangkat: "))
dtk_brkt = int(input("Detik Berangkat: "))
harga = int(input("Harga: "))
tgl_brkt = int(input("Tanggal Berangkat: "))
bln_brkt = str(input("Bulan Berangkat: "))
thn_brkt = int(input("Tahun Berangkat: "))
kelas = str(input("Kelas: "))
jam_kdtgn = int(input("Jam Kedatangan: "))
mnt_kdtgn = int(input("Menit Kedatangan: "))
dtk_kdtgn = int(input("Detik Kedatangan: "))

print("Tiket Travel Olala\n")
print("Nama Penumpang: ",nm_pnumpang)
print("No HP: ",no_hp)
print("Tujuan: ",tujuan)
print("Harga: ",harga)
print("Jam berangkat: ",jam_brkt,mnt_brkt,dtk_brkt)
